import { Injectable, signal, computed, effect } from '@angular/core';

export type Lang = 'es' | 'en';

export const translations = {
  es: {
    // Badge & availability
    available: 'Disponible para proyectos',
    unavailable: 'No disponible actualmente',
    // Nav
    nav_home: 'Inicio',
    nav_about: 'Sobre mí',
    nav_knowledge: 'Conocimientos',
    nav_projects: 'Proyectos',
    nav_contact: 'Contacto',
    nav_cv: 'CV Desarrollo',
    nav_theme_light: 'Modo claro',
    nav_theme_dark: 'Modo oscuro',
    // Hero
    hero_desc: 'Ingeniero de Software especializado en Desarrollo Frontend y Diseño UI/UX. Con 2 años de experiencia liderando productos y colaborando en equipos ágiles, transformo diseños funcionales en aplicaciones web y multiplataforma escalables con Angular, Tailwind CSS, .NET y SQL Server.',
    hero_cta_projects: 'Ver Proyectos',
    hero_cta_contact: 'Contáctame',
    hero_cta_cv: 'Descargar CV',
    hero_cta_cv_dev: 'CV Desarrollo',
    hero_cta_cv_it: 'CV Tecnología',
    stat_years: 'Años de experiencia',
    stat_projects: 'Proyectos destacados',
    tech_title: 'Tecnologías que uso',
    // Tech tooltips
    tech_tip_angular: 'Framework para aplicaciones web',
    tech_tip_typescript: 'Lenguaje con tipado estático',
    tech_tip_tailwind: 'Estilos y diseño responsivo',
    tech_tip_html5: 'Estructura y marcado semántico',
    tech_tip_css: 'Animaciones y efectos visuales',
    tech_tip_dotnet: 'Backend y APIs robustas',
    tech_tip_laravel: 'Framework PHP moderno',
    tech_tip_github_tooltip: 'Control de versiones',
    tech_tip_figma: 'Diseño UI/UX colaborativo',
    tech_tip_android: 'Desarrollo de apps Android',
    tech_tip_capacitor: 'Apps móviles híbridas',
    tech_tip_sql: 'SQL Server y Management Studio',
    // About
    section_about: 'Sobre mí',
    about_bio_title: 'Mi Historia',
    about_bio_p1: 'Soy Ingeniero de Software especializado en cerrar la brecha entre el diseño estético y la implementación técnica. Me enfoco en interfaces intuitivas, alto rendimiento, accesibilidad y código limpio.',
    about_bio_p2: 'He liderado diseño y frontend en productos reales, colaborando con equipos ágiles y construyendo plataformas web, móviles, SaaS, APIs REST y soluciones con fuerte base en TI, hardware y software.',
    about_edu_title: 'Educación',
    about_edu_degree: 'Lic. Ingeniería en Software',
    about_edu_uni: 'Universidad Politécnica de Pachuca • Sept 2022 - Sept 2025',
    about_edu_award: 'Reconocimiento institucional por 1er lugar en propuestas de aplicaciones de software para resolver problemas de la vida diaria; líder de diseño y frontend.',
    about_edu_cert: 'Certificado EF SET Inglés',
    about_edu_cert_sub: 'B2 Intermedio alto • 58/100 • 15-04-2025',
    about_services_title: 'Servicios',
    about_svc_1: 'Frontend con Angular 20/21, TypeScript y Tailwind CSS',
    about_svc_2: 'Backend con .NET, APIs REST y SQL Server',
    about_svc_3: 'Diseño UI/UX, prototipado y sistemas visuales',
    about_svc_4: 'PWAs y apps móviles híbridas con Capacitor',
    about_exp_title: 'Experiencia Laboral',
    badge_own: 'Proyecto Propio',
    badge_work: 'Proyecto Laboral',
    about_axio_desc: 'Desarrollador Full Stack & UI/UX Designer • Pachuca, Hgo. • Jul 2024 - Jul 2025',
    about_axio_1: 'Panel de noticias y blog corporativo',
    about_axio_2: 'Sistema de notificaciones interconectadas',
    about_axio_3: 'Integración de aplicaciones multiplataforma',
    about_axio_4: 'APIs REST y gestión de bases de datos',
    about_axio_5: 'Rediseño general para un sitio web multiplataforma',
    about_falcodex_desc: 'Co-Fundador, Lead Developer & Lead Designer • Pachuca, Hgo. • Jun 2025 - Abr 2026',
    about_falcodex_1: 'Co-fundador y líder técnico y de diseño de la startup.',
    about_falcodex_2: 'Diseño y desarrollo de EveryMed Landing Page con sección demo de la interfaz.',
    about_falcodex_3: 'Diseño y construcción de EveryMed desde cero.',
    about_falcodex_4: 'Áreas de enfoque: PWA/Web/Móvil Nativo, SaaS, UI/UX, APIs REST y Clean Architecture.',
    about_moncar_desc: 'UI/UX Designer & Front-End Developer • Pachuca, Hgo. • Feb 2026 - May 2026',
    about_moncar_1: 'Diseñador y analista de proyectos.',
    about_moncar_2: 'Diseño de landing pages y proyectos digitales.',
    about_moncar_3: 'Desarrollo front-end y testing de proyectos.',
    about_everymed_desc: 'Proyecto propio de gestión médica dentro de FALCodeX',
    about_everymed_1: 'Diseño responsive para web, PWA y móvil nativo',
    about_everymed_2: 'Autenticación, roles y expedientes compatibles con NOM-024-SSA3',
    about_everymed_3: 'Gestión de citas, notificaciones en tiempo real y Capacitor',
    about_everymed_4: 'Planes médicos, pagos y suscripciones con Stripe',
    about_everymed_5: 'Perfiles personalizables y dashboard analítico',
    about_everymed_6: 'Backend con .NET 9, SQL Server, JWT y Clean Architecture',
    about_everymed_7: 'Liderazgo de diseño y desarrollo backend con equipo mediano',
    about_skills_title: 'Habilidades',
    about_lang_title: 'Idiomas',
    about_lang_es_name: 'Español',
    about_lang_es_sub: 'Lengua nativa',
    about_lang_es_level: 'Nativo',
    about_lang_en_name: 'Inglés',
    about_lang_en_sub: 'B2 — Intermedio Alto · EF SET 58/100',
    // IT & Technology section
    section_knowledge: 'Conocimientos en TI y Tecnología',
    section_knowledge_sub: 'Más allá del desarrollo de software, cuento con conocimientos adquiridos a lo largo de mi carrera de ingeniería, experiencia práctica y hobbies en diversas áreas de la tecnología e informática.',
    ti_info_title: 'Informática General',
    ti_info_1: 'Microsoft Office Suite (Word, Excel, PowerPoint)',
    ti_info_2: 'Google Workspace (Docs, Sheets, Drive)',
    ti_info_3: 'Gestión y organización de archivos digitales',
    ti_info_4: 'Diagnóstico y resolución de problemas intermedios/avanzados en hardware y software',
    ti_info_5: 'Productividad digital con Notion',
    ti_soft_title: 'Software y Herramientas',
    ti_soft_1: 'IDEs: VS Code, Visual Studio, Rider, WebStorm',
    ti_soft_2: 'Pruebas de API: Postman e Insomnia',
    ti_soft_3: 'Diseño: Figma, v0, Adobe Illustrator/Canva, Affinity básico y editores de imagen/audio/video',
    ti_soft_4: 'Herramientas de IA: GitHub Copilot, ChatGPT, Claude',
    ti_hw_title: 'Hardware y Equipos',
    ti_hw_1: 'Componentes de PC: CPU, RAM, GPU, almacenamiento',
    ti_hw_2: 'Ensamblado y mantenimiento de equipos',
    ti_hw_3: 'Diagnóstico y reparación básica de fallas',
    ti_hw_4: 'Periféricos y dispositivos de entrada/salida',
    ti_hw_5: 'Electrónica básica y microcontroladores (Arduino)',
    ti_os_title: 'Sistemas Operativos',
    ti_os_windows_desc: 'Uso avanzado, configuración y administración',
    ti_os_linux_desc: 'Ubuntu, Manjaro; terminal, permisos y scripts bash',
    ti_os_macos_desc: 'Uso intermedio en entornos de desarrollo',
    ti_os_4: 'Virtualización con VirtualBox / Hyper-V',
    ti_os_5: 'WSL2 (Windows Subsystem for Linux)',
    ti_net_title: 'IT y Redes',
    ti_net_1: 'Fundamentos TCP/IP, DNS, DHCP y HTTP/HTTPS',
    ti_net_2: 'Configuración de redes domésticas y pequeñas empresas',
    ti_net_3: 'VPNs y conexiones seguras',
    ti_net_4: 'Servidores web: IIS, Nginx básico',
    ti_net_5: 'Despliegue en cloud: Azure, Vercel y MyASP.NET',
    ti_tech_title: 'Tecnología General',
    ti_tech_1: 'Seguimiento de tendencias tecnológicas e innovación',
    ti_tech_2: 'Inteligencia Artificial y modelos LLM aplicados al desarrollo',
    ti_tech_3: 'Cloud computing: despliegue, hosting y administración de servicios en Azure y Vercel',
    ti_music_title: 'Producción Musical e Instrumentos',
    ti_music_sub: 'Hobby y práctica autodidacta',
    ti_music_prod_title: 'Producción Digital (DAW)',
    ti_music_prod_1: 'Fender Studio Pro (anteriormente Studio One): composición, mezcla y arreglos',
    ti_music_prod_2: 'Uso de plugins VST, síntesis y samplers',
    ti_music_prod_3: 'Mezcla básica: EQ, compresión, reverb y delay',
    ti_music_prod_4: 'Diseño de sonido y sound design electrónico',
    ti_music_inst_title: 'Instrumentos',
    ti_music_inst_1: 'Guitarra eléctrica y acústica (nivel intermedio)',
    ti_music_inst_2: 'Piano/teclado MIDI: teoría básica y acordes',
    ti_music_inst_3: 'Bajo eléctrico: líneas rítmicas y acompañamiento',
    ti_music_inst_4: 'Lectura de tablaturas y cifrado americano',
    ti_music_maint_title: 'Mantenimiento y Equipo',
    ti_music_maint_1: 'Cambio de cuerdas y ajuste de acción e intonación',
    ti_music_maint_2: 'Configuración de pastillas y electrónica básica',
    ti_music_maint_3: 'Cadena de señal: interfaz de audio, amplificadores y efectos',
    ti_music_maint_4: 'Grabación de audio con interfaz y micrófonos',
    // FALCodeX
    falcodex_startup: 'Startup de desarrollo de software',
    falcodex_cofound: 'Co-Fundador',
    falcodex_what_title: '¿Qué es FALCodeX?',
    falcodex_desc_1: 'FALCodeX es la startup de desarrollo de software de la que soy co-fundador, Lead Developer y Lead Designer. Desde ahí diseño y construyo productos web, móviles, SaaS, sistemas UI/UX, APIs REST y arquitecturas limpias.',
    falcodex_desc_2: 'Bajo el nombre de FALCodeX nacen los proyectos más ambiciosos de mi carrera, incluyendo',
    falcodex_desc_2b: '— plataforma completa de gestión médica desarrollada desde cero con arquitectura propia.',
    falcodex_focus_title: 'Áreas de enfoque',
    falcodex_focus_1: 'Aplicaciones web y móviles (PWA / Android)',
    falcodex_focus_2: 'SaaS y plataformas de gestión empresarial',
    falcodex_focus_3: 'Diseño UI/UX y sistemas de diseño',
    falcodex_focus_4: 'APIs REST y arquitecturas limpias',
    falcodex_focus_5: 'Consultoría y desarrollo a medida',
    falcodex_stack_title: 'Stack principal en FALCodeX',
    // Projects
    section_projects: 'Proyectos',
    filter_all: 'Todos',
    filter_frontend: 'Frontend',
    filter_backend: 'Backend',
    filter_fullstack: 'Full Stack',
    proj_visit: 'Visitar sitio',
    proj_more: 'Ver más proyectos',
    proj_github_label: 'en mi GitHub',
    proj_everymed_admin_desc: 'Aplicación web progresiva y móvil nativa de gestión médica desarrollada con Angular 20/21. Incluye expedientes, citas, roles, Stripe, Capacitor y dashboard analítico.',
    proj_everymed_api_desc: 'API REST robusta en .NET 9 con Clean Architecture, SOLID, JWT, roles, Entity Framework Core, SQL Server, MailKit y notificaciones en tiempo real.',
    proj_everymed_landing_desc: 'Landing page moderna y responsive para EveryMed con sección demo para mostrar la interfaz de administración con animaciones suaves.',
    proj_guiart_desc: 'Nuevo concepto de plataforma de cursos de FALCodeX, con landing pública y app web separada para construir una experiencia de aprendizaje visual y escalable.',
    proj_axio_desc: 'Plataforma administrativa y sitio multiplataforma para cursos, aprendizaje, noticias, blog corporativo y notificaciones interconectadas.',
    page_about_title: 'Perfil profesional',
    page_about_intro: 'Una vista resumida de mi trayectoria, stack y enfoque de trabajo: 2 años de experiencia y 9 proyectos destacados alineados con mi CV actualizado.',
    page_projects_title: 'Proyectos destacados',
    page_projects_intro: '9 proyectos propios, laborales y productos en desarrollo alineados con mi CV actualizado en abril de 2026.',
    page_contact_title: 'Hablemos de tu proyecto',
    page_contact_intro: 'Estoy disponible para colaborar en productos web, APIs, PWAs, interfaces y soluciones digitales a medida.',
    page_back_home: 'Volver al inicio',
    page_view_full_profile: 'Ver perfil completo',
    page_view_contact: 'Ir a contacto',
    page_view_projects: 'Ver proyectos',
    project_features_title: 'Características principales',
    project_stack_title: 'Stack tecnológico',
    project_architecture_title: 'Arquitectura',
    // Contact
    section_contact: 'Contacto',
    contact_send_msg: 'Envíame un mensaje',
    contact_name: 'Nombre',
    contact_name_ph: 'Tu nombre',
    contact_email: 'Email',
    contact_subject: 'Asunto',
    contact_subject_ph: '¿En qué puedo ayudarte?',
    contact_message: 'Mensaje',
    contact_message_ph: 'Cuéntame sobre tu proyecto...',
    contact_submit: 'Enviar mensaje',
    contact_sending: 'Enviando...',
    contact_success: '✓ Mensaje enviado correctamente. Te responderé pronto.',
    contact_error: '✗ Error al enviar el mensaje. Por favor, intenta nuevamente.',
    contact_err_name: 'El nombre es requerido (mínimo 2 caracteres)',
    contact_err_email: 'Ingresa un email válido',
    contact_err_subject: 'El asunto es requerido (mínimo 3 caracteres)',
    contact_err_message: 'El mensaje es requerido (mínimo 10 caracteres)',
    contact_tel_label: 'Teléfono',
    contact_location_label: 'Ubicación',
    lang_toggle: 'English',
  },
  en: {
    // Badge & availability
    available: 'Available for projects',
    unavailable: 'Not available right now',
    // Nav
    nav_home: 'Home',
    nav_about: 'About Me',
    nav_knowledge: 'Knowledge',
    nav_projects: 'Projects',
    nav_contact: 'Contact',
    nav_cv: 'Dev CV',
    nav_theme_light: 'Light mode',
    nav_theme_dark: 'Dark mode',
    // Hero
    hero_desc: 'Software Engineer specialized in Frontend Development and UI/UX Design. With 2 years of experience leading products and collaborating in agile teams, I turn functional designs into scalable web and cross-platform applications with Angular, Tailwind CSS, .NET and SQL Server.',
    hero_cta_projects: 'View Projects',
    hero_cta_contact: 'Contact Me',
    hero_cta_cv: 'Download CV',
    hero_cta_cv_dev: 'Dev CV',
    hero_cta_cv_it: 'IT CV',
    stat_years: 'Years of experience',
    stat_projects: 'Featured projects',
    tech_title: 'Technologies I use',
    // Tech tooltips
    tech_tip_angular: 'Web application framework',
    tech_tip_typescript: 'Statically typed language',
    tech_tip_tailwind: 'Styles and responsive design',
    tech_tip_html5: 'Semantic structure and markup',
    tech_tip_css: 'Animations and visual effects',
    tech_tip_dotnet: 'Backend and robust APIs',
    tech_tip_laravel: 'Modern PHP framework',
    tech_tip_github_tooltip: 'Version control',
    tech_tip_figma: 'Collaborative UI/UX design',
    tech_tip_android: 'Android app development',
    tech_tip_capacitor: 'Hybrid mobile apps',
    tech_tip_sql: 'SQL Server and Management Studio',
    // About
    section_about: 'About Me',
    about_bio_title: 'My Story',
    about_bio_p1: "I'm a Software Engineer specialized in closing the gap between aesthetic design and technical implementation. I focus on intuitive interfaces, high performance, accessibility and clean code.",
    about_bio_p2: 'I have led design and frontend work on real products, collaborating with agile teams and building web, mobile, SaaS, REST API and IT-backed software solutions.',
    about_edu_title: 'Education',
    about_edu_degree: 'B.S. Software Engineering',
    about_edu_uni: 'Universidad Politécnica de Pachuca • Sept 2022 - Sept 2025',
    about_edu_award: 'Institutional recognition for 1st place in software application proposals that solve daily-life problems; design and frontend lead.',
    about_edu_cert: 'EF SET English Certificate',
    about_edu_cert_sub: 'B2 Upper Intermediate • 58/100 • 04-15-2025',
    about_services_title: 'Services',
    about_svc_1: 'Frontend with Angular 20/21, TypeScript and Tailwind CSS',
    about_svc_2: 'Backend with .NET, REST APIs and SQL Server',
    about_svc_3: 'UI/UX design, prototyping and visual systems',
    about_svc_4: 'PWAs and hybrid mobile apps with Capacitor',
    about_exp_title: 'Work Experience',
    badge_own: 'Own Project',
    badge_work: 'Work Project',
    about_axio_desc: 'Full Stack Developer & UI/UX Designer • Pachuca, Hgo. • Jul 2024 - Jul 2025',
    about_axio_1: 'News panel and corporate blog',
    about_axio_2: 'Interconnected notification system',
    about_axio_3: 'Cross-platform application integration',
    about_axio_4: 'REST APIs and database management',
    about_axio_5: 'Full redesign for a cross-platform website',
    about_falcodex_desc: 'Co-Founder, Lead Developer & Lead Designer • Pachuca, Hgo. • Jun 2025 - Apr 2026',
    about_falcodex_1: 'Co-founder and technical/design lead of the startup.',
    about_falcodex_2: 'Designed and built the EveryMed Landing Page with a UI demo section.',
    about_falcodex_3: 'Designed and built EveryMed from scratch.',
    about_falcodex_4: 'Focus areas: PWA/Web/Native Mobile, SaaS, UI/UX, REST APIs and Clean Architecture.',
    about_moncar_desc: 'UI/UX Designer & Front-End Developer • Pachuca, Hgo. • Feb 2026 - May 2026',
    about_moncar_1: 'Project designer and analyst.',
    about_moncar_2: 'Landing page and digital project designer.',
    about_moncar_3: 'Frontend development and project testing.',
    about_everymed_desc: 'Own medical management project within FALCodeX',
    about_everymed_1: 'Responsive design for web, PWA and native mobile',
    about_everymed_2: 'Authentication, roles and NOM-024-SSA3 compatible records',
    about_everymed_3: 'Appointments, real-time notifications and Capacitor',
    about_everymed_4: 'Medical plans, payments and Stripe subscriptions',
    about_everymed_5: 'Custom profiles and analytics dashboard',
    about_everymed_6: 'Backend with .NET 9, SQL Server, JWT and Clean Architecture',
    about_everymed_7: 'Design leadership and backend development with a mid-sized team',
    about_skills_title: 'Skills',
    about_lang_title: 'Languages',
    about_lang_es_name: 'Spanish',
    about_lang_es_sub: 'Native language',
    about_lang_es_level: 'Native',
    about_lang_en_name: 'English',
    about_lang_en_sub: 'B2 — Upper Intermediate · EF SET 58/100',
    // IT & Technology section
    section_knowledge: 'IT & Technology Knowledge',
    section_knowledge_sub: 'Beyond software development, I have knowledge acquired throughout my engineering career, hands-on experience and hobbies in various areas of technology and computing.',
    ti_info_title: 'General Computing',
    ti_info_1: 'Microsoft Office Suite (Word, Excel, PowerPoint)',
    ti_info_2: 'Google Workspace (Docs, Sheets, Drive)',
    ti_info_3: 'Digital file management and organization',
    ti_info_4: 'Intermediate/advanced hardware and software troubleshooting',
    ti_info_5: 'Digital productivity with Notion',
    ti_soft_title: 'Software & Tools',
    ti_soft_1: 'IDEs: VS Code, Visual Studio, Rider, WebStorm',
    ti_soft_2: 'API testing: Postman and Insomnia',
    ti_soft_3: 'Design: Figma, v0, Adobe Illustrator/Canva, basic Affinity and image/audio/video editors',
    ti_soft_4: 'AI tools: GitHub Copilot, ChatGPT, Claude',
    ti_hw_title: 'Hardware & Equipment',
    ti_hw_1: 'PC components: CPU, RAM, GPU, storage',
    ti_hw_2: 'PC assembly and maintenance',
    ti_hw_3: 'Basic fault diagnosis and repair',
    ti_hw_4: 'Peripherals and input/output devices',
    ti_hw_5: 'Basic electronics and microcontrollers (Arduino)',
    ti_os_title: 'Operating Systems',
    ti_os_windows_desc: 'Advanced use, configuration and administration',
    ti_os_linux_desc: 'Ubuntu, Manjaro; terminal, permissions and bash scripts',
    ti_os_macos_desc: 'Intermediate use in development environments',
    ti_os_4: 'Virtualization with VirtualBox / Hyper-V',
    ti_os_5: 'WSL2 (Windows Subsystem for Linux)',
    ti_net_title: 'IT & Networks',
    ti_net_1: 'TCP/IP, DNS, DHCP and HTTP/HTTPS fundamentals',
    ti_net_2: 'Home and small business network configuration',
    ti_net_3: 'VPNs and secure connections',
    ti_net_4: 'Web servers: IIS, basic Nginx',
    ti_net_5: 'Cloud deployment: Azure, Vercel and MyASP.NET',
    ti_tech_title: 'General Technology',
    ti_tech_1: 'Tracking technological trends and innovation',
    ti_tech_2: 'Artificial Intelligence and LLM models applied to development',
    ti_tech_3: 'Cloud computing: deployment, hosting and service management on Azure and Vercel',
    ti_music_title: 'Music Production & Instruments',
    ti_music_sub: 'Hobby and self-taught practice',
    ti_music_prod_title: 'Digital Production (DAW)',
    ti_music_prod_1: 'Fender Studio Pro (formerly Studio One): composition, mixing and arrangements',
    ti_music_prod_2: 'VST plugin use, synthesis and samplers',
    ti_music_prod_3: 'Basic mixing: EQ, compression, reverb and delay',
    ti_music_prod_4: 'Sound design and electronic sound design',
    ti_music_inst_title: 'Instruments',
    ti_music_inst_1: 'Electric and acoustic guitar (intermediate level)',
    ti_music_inst_2: 'Piano/MIDI keyboard: basic theory and chords',
    ti_music_inst_3: 'Electric bass: rhythmic lines and accompaniment',
    ti_music_inst_4: 'Reading tablature and chord charts',
    ti_music_maint_title: 'Maintenance & Equipment',
    ti_music_maint_1: 'String changes and action/intonation setup',
    ti_music_maint_2: 'Pickup setup and basic electronics',
    ti_music_maint_3: 'Signal chain: audio interface, amplifiers and effects',
    ti_music_maint_4: 'Audio recording with interface and microphones',
    // FALCodeX
    falcodex_startup: 'Software development startup',
    falcodex_cofound: 'Co-Founder',
    falcodex_what_title: 'What is FALCodeX?',
    falcodex_desc_1: 'FALCodeX is the software development startup I co-founded as Lead Developer and Lead Designer. From there I design and build web, mobile, SaaS, UI/UX systems, REST APIs and clean architectures.',
    falcodex_desc_2: 'Under the FALCodeX name, the most ambitious projects of my career come to life, including',
    falcodex_desc_2b: '— a complete medical management platform built from scratch with its own architecture.',
    falcodex_focus_title: 'Focus areas',
    falcodex_focus_1: 'Web and mobile applications (PWA / Android)',
    falcodex_focus_2: 'SaaS and business management platforms',
    falcodex_focus_3: 'UI/UX design and design systems',
    falcodex_focus_4: 'REST APIs and clean architectures',
    falcodex_focus_5: 'Custom consulting and development',
    falcodex_stack_title: 'Main stack at FALCodeX',
    // Projects
    section_projects: 'Projects',
    filter_all: 'All',
    filter_frontend: 'Frontend',
    filter_backend: 'Backend',
    filter_fullstack: 'Full Stack',
    proj_visit: 'Visit site',
    proj_more: 'See more projects',
    proj_github_label: 'on my GitHub',
    proj_everymed_admin_desc: 'Progressive web and native mobile medical management app built with Angular 20/21. Includes records, appointments, roles, Stripe, Capacitor and analytics dashboard.',
    proj_everymed_api_desc: 'Robust REST API in .NET 9 with Clean Architecture, SOLID, JWT, roles, Entity Framework Core, SQL Server, MailKit and real-time notifications.',
    proj_everymed_landing_desc: 'Modern responsive landing page for EveryMed with a demo section that previews the administration interface with smooth animations.',
    proj_guiart_desc: 'New FALCodeX course platform concept, with a public landing page and a separate web app to build a visual and scalable learning experience.',
    proj_axio_desc: 'Administrative platform and cross-platform site for courses, learning, news, corporate blog and interconnected notifications.',
    page_about_title: 'Professional profile',
    page_about_intro: 'A concise view of my background, stack and working approach: 2 years of experience and 9 featured projects aligned with my updated resume.',
    page_projects_title: 'Featured projects',
    page_projects_intro: '9 personal, work and in-progress products aligned with my resume last updated in April 2026.',
    page_contact_title: 'Let’s talk about your project',
    page_contact_intro: 'I am available to collaborate on web products, APIs, PWAs, interfaces and custom digital solutions.',
    page_back_home: 'Back home',
    page_view_full_profile: 'View full profile',
    page_view_contact: 'Go to contact',
    page_view_projects: 'View projects',
    project_features_title: 'Main features',
    project_stack_title: 'Tech stack',
    project_architecture_title: 'Architecture',
    // Contact
    section_contact: 'Contact',
    contact_send_msg: 'Send me a message',
    contact_name: 'Name',
    contact_name_ph: 'Your name',
    contact_email: 'Email',
    contact_subject: 'Subject',
    contact_subject_ph: 'How can I help you?',
    contact_message: 'Message',
    contact_message_ph: 'Tell me about your project...',
    contact_submit: 'Send message',
    contact_sending: 'Sending...',
    contact_success: "✓ Message sent successfully. I'll get back to you soon.",
    contact_error: '✗ Failed to send message. Please try again.',
    contact_err_name: 'Name is required (minimum 2 characters)',
    contact_err_email: 'Enter a valid email address',
    contact_err_subject: 'Subject is required (minimum 3 characters)',
    contact_err_message: 'Message is required (minimum 10 characters)',
    contact_tel_label: 'Phone',
    contact_location_label: 'Location',
    lang_toggle: 'Español',
  },
} as const;

export type TranslationKey = keyof typeof translations.es;

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly lang = signal<Lang>('es');
  readonly current = computed(() => translations[this.lang()]);

  constructor() {
    effect(() => {
      document.documentElement.lang = this.lang();
    });
  }

  toggle(): void {
    this.lang.update(l => (l === 'es' ? 'en' : 'es'));
  }
}
